watches:
  - name: "Lukas Widegren ranking"
    connector: sgf_ranking
    mode: daily
    player: "Lukas Widegren"

  - name: "Lukas Widegren live"
    connector: golfbox_leaderboard
    mode: live
    competition: 5543525
    player: "Lukas Widegren"

  - name: "Lukas Widegren Tournytt"
    connector: tournytt_api
    mode: live
    competition: 5406076
    player: "Lukas Widegren"

ntfy:
  topic: "tom-widegren-golf-92fd71b8"
